#开发环境配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

mybatis:
  type-aliases-package: com.xsh.pojo   #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件
logging:
  level:
    root: info #设置全局日志级别，此处默认为info,生产环境可设置为更高级别的warn
    com.xsh: debug #指定对应目录的日志级别，在此目录内的日志级别为debug

  file: log/blog-dev.log #设置日志存放目录